pregled/urls.py
from django.urls import path, register_converter
from django.conf import settings

from . import views
import converters

register_converter(converters.makeConverter(settings.HASHIDS_SALT['main']), 'mhash')
register_converter(converters.makeConverter(settings.HASHIDS_SALT['ekipa']), 'ehash')
register_converter(converters.makeConverter(settings.HASHIDS_SALT['info']), 'ihash')
register_converter(converters.makeConverter(settings.HASHIDS_SALT['rez_view']), 'rv_hash')

app_name = 'pregled'
urlpatterns = [
    path('<mhash:key>/', views.index, name = 'index'),
    path('import_export/<mhash:key>/', views.file.import_export, name = 'import_export'),
    path('download/<mhash:key>/', views.file.download, name = 'download'),
    path('upload/<mhash:key>/', views.file.upload, name = 'upload'),
    path('kontrole/<mhash:key>/', views.kontrole, name = 'kontrole'),
    path('proge/<mhash:key>/', views.proge, name = 'proge'),
    path('ekipe/<mhash:key>/', views.ekipe, name = 'ekipe'),
    path('rezultati/<mhash:key>/', views.rezultati, name = 'rezultati'),
    path('rezultati/v/<rv_hash:key>/', views.rezultati_v, name = 'rezultati_v'),

    path('info/<mhash:key>/<int:ekipa_id>/', views.info.ekipa, name = 'info_ekipa'),
    path('info/<mhash:key>/', views.info.index, name = 'info_index'),
    path('info/<ihash:key>/<str:ime>/', views.info.view, name = 'info_view'),
    path('info/<ihash:key>/', views.info.view, name = 'info_view'),

    path('obvestila/<mhash:key>/', views.obvestilo.obvestila, name = 'obvestila'),
    path('obvestilo/<mhash:key>/<int:obvestilo_id>', views.obvestilo.obvestilo,
        name = 'obvestilo'),
    path('obvestilo/<mhash:key>/new', views.obvestilo.novo_obvestilo,
        name = 'novo_obvestilo'),
    path('obvestilo/<mhash:key>/brisi/<int:obvestilo_id>', views.obvestilo.del_obvestilo,
        name = 'del_obvestilo'),

    path('qr_kontrole/<mhash:key>/', views.qr.kontrole, name = 'qr_kontrole'),
    path('qr_ekipe/<mhash:key>/', views.qr.ekipe, name = 'qr_ekipe'),

    path('<ehash:key>/', views.ekipa.index, name = 'ekipa_index'),
    path('obvestila/<ehash:key>/', views.ekipa.obvestila,
        name = 'ekipa_obvestila'),
    path('obvestila/<ehash:key>/mark_read/<int:obvestilo_id>',
        views.ekipa.mark_read, name = 'mark_read'),
    path('info/<ehash:key>/', views.ekipa.info, name = 'ekipa_info'),
]

struktura/urls.py
from django.urls import path, register_converter
from django.conf import settings

from . import views
import converters

register_converter(converters.makeConverter(
    settings.HASHIDS_SALT['rezultat']), 'rhash')
register_converter(converters.makeConverter(
    settings.HASHIDS_SALT['struktura']), 'shash')
register_converter(converters.makeConverter(
    settings.HASHIDS_SALT['kontrola']), 'khash')

app_name = 'struktura'
urlpatterns = [
    path('tekmovanje/<shash:key>/', views.v_tekmovanje, name='tekmovanje'),
]

for modelname in ['kategorija', 'dan', 'kt', 'ekipa', 'proga', 'kontrola', 'naloga']:
    for op in ['', 'edit', 'add', 'rm']:
        cname = modelname
        if op != '':
            cname += '_' + op
        cpath = cname.replace('_', '/') + '/<shash:key>/'
        if op in ['edit', 'rm']:
            cpath += '<shash:obj_key>/'
        cview = getattr(views, 'v_' + cname),
        urlpatterns.append(path(cpath, *cview, name=cname))

urlpatterns.append(path('rezultat/<khash:key>', views.v_rezultat, name='rezultat'))
urlpatterns.append(path('rezultat/a/<khash:key>/<khash:kat_key>', views.v_rezultat_add, name='rezultat_add'))
urlpatterns.append(path('rezultat/e/<khash:key>/<khash:eki_key>', views.v_rezultat_edit, name='rezultat_edit'))
urlpatterns.append(path('rezultat/r/<khash:key>/<khash:eki_key>', views.v_rezultat_rm, name='rezultat_rm'))

urlpatterns.append(path('rezultati/<rhash:key>/',
                        views.rezultati, name='rezultati'))
urlpatterns.append(path('pregled_ekipe/<rhash:key>/',
                   views.pregled_ekipe, name='pregled_ekipe'))

volcjak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('struktura/', include('struktura.urls')),
    path('pregled/', include('pregled.urls')),
    path('admin/', admin.site.urls),
    path('qr_code/', include('qr_code.urls', namespace='qr_code')),
]

struktura/views/dan.py
from django.db.models import deletion
from django.shortcuts import render, get_object_or_404
from django import forms
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from datetime import date, timedelta

from ..models import Tekmovanje, Dan


class DanForm(forms.ModelForm):

    datum = forms.DateField(widget=forms.TextInput(attrs={'pattern': '\d\d\d\d-\d\d?-\d\d?',
                                                          'placeholder': '2022-7-21'}))

    class Meta:
        model = Dan
        exclude = ['tekmovanje']
        localized_fields = ('datum',)


def default_context(key):
    return {'key': key, 'sec_name': 'dan', 'display_name': 'Dan',
            'plural_name': 'dnevi'}


def v_dan(request, key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['objs'] = tekmovanje.dan_set.all()
    return render(request, 'struktura/index.html', context)


def v_dan_edit(request, key, obj_key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['obj'] = dan = get_object_or_404(Dan, pk=obj_key)
    context['submit_buttons'] = [
            {'val': 'shrani', 'name': 'save'},
            {'val': 'shrani in zapri', 'name': 'save_and_exit'},
            {'val': 'prekliči', 'name': 'cancel'}
            ]
    if dan.tekmovanje != tekmovanje:
        raise Http404("Dan not of right tekmovanje!")
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('struktura:dan', args=[key]))
        form = DanForm(data=request.POST, instance=dan)
        if form.is_valid():
            form.save()
            if 'save_and_exit' in request.POST:
                return HttpResponseRedirect(reverse('struktura:dan', args=[key]))
    else:
        form = DanForm(instance=dan)
    context['form'] = form
    return render(request, 'struktura/edit.html', context)


def v_dan_add(request, key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['submit_buttons'] = [
            {'val': 'shrani in zapri', 'name': 'save_and_exit'},
            {'val': 'shrani in uredi', 'name': 'save_and_edit'},
            {'val': 'shrani in dodaj novo', 'name': 'save_and_add_another'},
            {'val': 'shrani in dodaj podobno', 'name': 'save_and_add_similar'},
            {'val': 'prekliči', 'name': 'cancel'}
            ]
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('struktura:dan', args=[key]))
        form = DanForm(data=request.POST)
        if form.is_valid():
            dan = form.save(commit=False)
            dan.tekmovanje = tekmovanje
            dan.save()
            if 'save_and_exit' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:dan', args=[key]))
            if 'save_and_edit' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:dan_edit', args=[key, dan.pk]))
            if 'save_and_add_another' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:dan_add', args=[key]))
            if 'save_and_add_similar' in request.POST:
                data = request.POST.copy()
                data['st'] = int(data['st']) + 1
                data['datum'] = date.fromisoformat(data['datum']) + timedelta(1)
                form = DanForm(data=data)
    else:
        form = DanForm()
    context['form'] = form
    return render(request, 'struktura/add.html', context)


def v_dan_rm(request, key, obj_key):
    dan = get_object_or_404(Dan, pk=obj_key)
    if dan.tekmovanje.pk == key:
        try:
            dan.delete()
            return HttpResponse('Successfully deleted Dan [{}]!'.format(str(dan)), status=200)
        except deletion.RestrictedError:
            return HttpResponse('Dan [{}] not deleted because of restricted foreign keys!'.format(str(dan)), status=500)
    return HttpResponse('Dan does not match tekmovanje pk, deletion refused!', status=403)

struktura/views/ekipa.py
from django.db.models import deletion
from django.shortcuts import render, get_object_or_404
from django import forms
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from ..models import Tekmovanje, Kategorija, Ekipa


def get_EkipaForm(qs):
    class EkipaForm(forms.ModelForm):
        kategorija = forms.ModelChoiceField(queryset=qs)

        class Meta:
            model = Ekipa
            exclude = []
    return EkipaForm


def default_context(key):
    return {'key': key, 'sec_name': 'ekipa', 'display_name': 'Ekipa',
            'plural_name': 'Ekipe'}


def v_ekipa(request, key):
    context = default_context(key)
    context['tekmovanje'] = get_object_or_404(Tekmovanje, pk=key)
    context['objs'] = Ekipa.objects.filter(kategorija__tekmovanje=key)
    return render(request, 'struktura/index.html', context)


def v_ekipa_edit(request, key, obj_key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['obj'] = ekipa = get_object_or_404(Ekipa, pk=obj_key)
    context['submit_buttons'] = [
            {'val': 'shrani', 'name': 'save'},
            {'val': 'shrani in zapri', 'name': 'save_and_exit'},
            {'val': 'prekliči', 'name': 'cancel'}
            ]
    if ekipa.tekmovanje != tekmovanje:
        raise Http404("Ekipa not of right tekmovanje!")
    qs = Kategorija.objects.filter(tekmovanje=key)
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('struktura:ekipa', args=[key]))
        form = get_EkipaForm(qs)(data=request.POST, instance=ekipa)
        if form.is_valid():
            form.save()
            if 'save_and_exit' in request.POST:
                return HttpResponseRedirect(reverse('struktura:ekipa', args=[key]))
    else:
        form = get_EkipaForm(qs)(instance=ekipa)
    context['form'] = form
    return render(request, 'struktura/edit.html', context)


def v_ekipa_add(request, key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['submit_buttons'] = [
            {'val': 'shrani in zapri', 'name': 'save_and_exit'},
            {'val': 'shrani in uredi', 'name': 'save_and_edit'},
            {'val': 'shrani in dodaj novo', 'name': 'save_and_add_another'},
            {'val': 'shrani in dodaj podobno', 'name': 'save_and_add_similar'},
            {'val': 'prekliči', 'name': 'cancel'}
            ]
    qs = Kategorija.objects.filter(tekmovanje=key)
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('struktura:ekipa', args=[key]))
        form = get_EkipaForm(qs)(data=request.POST)
        if form.is_valid():
            ekipa = form.save(commit=False)
            ekipa.save()
            if 'save_and_exit' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:ekipa', args=[key]))
            if 'save_and_edit' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:ekipa_edit', args=[key, ekipa.pk]))
            if 'save_and_add_another' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:ekipa_add', args=[key]))
            if 'save_and_add_similar' in request.POST:
                data = request.POST.copy()
                data['stevilka'] = int(data['stevilka']) + 1
                form = get_EkipaForm(qs)(data=data)
    else:
        form = get_EkipaForm(qs)()
    context['form'] = form
    return render(request, 'struktura/add.html', context)


def v_ekipa_rm(request, key, obj_key):
    ekipa = get_object_or_404(Ekipa, pk=obj_key)
    if ekipa.kategorija.tekmovanje.pk == key:
        try:
            ekipa.delete()
            return HttpResponse('Successfully deleted Ekipa [{}]!'.format(str(ekipa)), status=200)
        except deletion.RestrictedError:
            return HttpResponse('Ekipa [{}] not deleted because of restricted foreign keys!'.format(str(ekipa)), status=500)
    return HttpResponse('Ekipa does not match tekmovanje pk, deletion refused!', status=403)

struktura/views/kategorija.py
from django.db.models import deletion
from django.shortcuts import render, get_object_or_404
from django import forms
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from ..models import Tekmovanje, Kategorija


class KategorijaForm(forms.ModelForm):

    class Meta:
        model = Kategorija
        exclude = ['tekmovanje']


def default_context(key):
    return {'key': key, 'sec_name': 'kategorija', 'display_name': 'Kategorija',
            'plural_name': 'kategorije'}


def v_kategorija(request, key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['objs'] = tekmovanje.kategorija_set.all()
    return render(request, 'struktura/index.html', context)


def v_kategorija_edit(request, key, obj_key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['obj'] = kategorija = get_object_or_404(Kategorija, pk=obj_key)
    context['submit_buttons'] = [
            {'val': 'shrani', 'name': 'save'},
            {'val': 'shrani in zapri', 'name': 'save_and_exit'},
            {'val': 'prekliči', 'name': 'cancel'}
            ]
    if kategorija.tekmovanje != tekmovanje:
        raise Http404("Kategorija not of right tekmovanje!")
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('struktura:kategorija', args=[key]))
        form = KategorijaForm(data=request.POST, instance=kategorija)
        if form.is_valid():
            form.save()
            if 'save_and_exit' in request.POST:
                return HttpResponseRedirect(reverse('struktura:kategorija', args=[key]))
    else:
        form = KategorijaForm(instance=kategorija)
    context['form'] = form
    return render(request, 'struktura/edit.html', context)


def v_kategorija_add(request, key):
    context = default_context(key)
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    context['submit_buttons'] = [
            {'val': 'shrani in zapri', 'name': 'save_and_exit'},
            {'val': 'shrani in uredi', 'name': 'save_and_edit'},
            {'val': 'shrani in dodaj novo', 'name': 'save_and_add_another'},
            {'val': 'shrani in dodaj podobno', 'name': 'save_and_add_similar'},
            {'val': 'prekliči', 'name': 'cancel'}
            ]
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('struktura:kategorija', args=[key]))
        form = KategorijaForm(data=request.POST)
        if form.is_valid():
            kategorija = form.save(commit=False)
            kategorija.tekmovanje = tekmovanje
            kategorija.save()
            if 'save_and_exit' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:kategorija', args=[key]))
            if 'save_and_edit' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:kategorija_edit', args=[key, kategorija.pk]))
            if 'save_and_add_another' in request.POST:
                return HttpResponseRedirect(
                        reverse('struktura:kategorija_add', args=[key]))
    else:
        form = KategorijaForm()
    context['form'] = form
    return render(request, 'struktura/add.html', context)


def v_kategorija_rm(request, key, obj_key):
    kategorija = get_object_or_404(Kategorija, pk=obj_key)
    if kategorija.tekmovanje.pk == key:
        try:
            kategorija.delete()
            return HttpResponse('Successfully deleted Kategorija [{}]!'.format(str(kategorija)), status=200)
        except deletion.RestrictedError:
            return HttpResponse('Kategorija [{}] not deleted because of restricted foreign keys!'.format(str(kategorija)), status=500)
    return HttpResponse('Kategorija does not match tekmovanje pk, deletion refused!', status=403)

struktura/views/tekmovanje.py
from django.shortcuts import render, get_object_or_404
from django import forms

from ..models import Tekmovanje


class TekmovanjeForm(forms.ModelForm):

    class Meta:
        model = Tekmovanje
        exclude = []


def v_tekmovanje(request, key):
    context = {'sec_name': 'tekmovanje', 'key': key}
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk=key)
    if request.method == 'POST':
        form = TekmovanjeForm(data=request.POST, instance=tekmovanje)
        if form.is_valid():
            form.save()
    else:
        form = TekmovanjeForm(instance=tekmovanje)
    context['form'] = form
    return render(request, 'struktura/tekmovanje.html', context)

struktura/templates/struktura/add.html
{% extends 'struktura/base.html' %}
{% load static %}

{% block title %}Volčjak struktura {{ plural_name }} {{ tekmovanje }} {% endblock %}

{% block content %}
	<h1>{{ display_name }}</h1>
	<form action="{% url 'struktura:'|add:sec_name|add:'_add' key %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		{% for butval in submit_buttons %}
		<input type="submit" value="{{ butval.val }}" name="{{ butval.name }}"/>
		{% endfor %}
	</form>
{% endblock content %}

struktura/templates/struktura/base.html
{% extends 'base.html' %}

{% block scripts %}
	<script>
		$(document).ready(function(){
			$('#nav-li-{{ sec_name }}').addClass('nav-selected');
		});
	</script>
{% endblock scripts %}

{% block mainnav %}
<ul>
	<li id="nav-li-tekmovanje"><a href="{% url 'struktura:tekmovanje' key %}">tekmovanje</a></li>
	<li id="nav-li-kategorija"><a href="{% url 'struktura:kategorija' key %}">kategorija</a></li>
	<li id="nav-li-dan"><a href="{% url 'struktura:dan' key %}">dan</a></li>
	<li id="nav-li-kt"><a href="{% url 'struktura:kt' key %}">kt</a></li>
	<li id="nav-li-ekipa"><a href="{% url 'struktura:ekipa' key %}">ekipa</a></li>
	<li id="nav-li-proga"><a href="{% url 'struktura:proga' key %}">proga</a></li>
	<li id="nav-li-kontrola"><a href="{% url 'struktura:kontrola' key %}">kontrola</a></li>
	<li id="nav-li-naloga"><a href="{% url 'struktura:naloga' key %}">naloga</a></li>
</ul>
{% endblock mainnav %}

struktura/templates/struktura/edit.html
{% extends 'struktura/base.html' %}
{% load static %}

{% block title %}Volčjak struktura {{ plural_name }} {{ tekmovanje }} {% endblock %}

{% block content %}
	<h1>{{ display_name }}</h1>
	<form action="{% url 'struktura:'|add:sec_name|add:'_edit' key obj.pk %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		{% for butval in submit_buttons %}
		<input type="submit" value="{{ butval.val }}" name="{{ butval.name }}"/>
		{% endfor %}
	</form>
{% endblock content %}

struktura/templates/struktura/rezultat.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
	{% csrf_token %}
	<script>
		const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
		$(document).ready(function(){
			$("#tabs").tabs();
			$('button.delete-rezultat').dblclick(function (){
				var button = this;
				var url = $(button).attr('href');
				$.ajax({
					url: url,
					type: 'POST',
					headers: { 'X-CSRFToken': csrftoken},
					success: function(data, textStatus, xhr){
						$(button).closest('li').remove();
						console.log("Deleted rezultats successfully!");
					},
					error: function(xhr, textStatus, ErrorThrown){
						console.log(textStatus, ErrorThrown, xhr);
						var errorMessage = xhr.responseText;
						if(errorMessage.indexOf('<title>') != -1)
							errorMessage = errorMessage.substring(errorMessage.indexOf('<title>') + 7, errorMessage.indexOf('</title>'));
						alert("Unable to delete rezultats: '" + errorMessage + "'");
					}
				});
			});
		});
	</script>
{% endblock scripts %}


{% block title %}Volčjak struktura {{ kt }} {% endblock %}

{% block content %}
	<h1>{{ kt }} {{ kontrola.ime }}</h1>
	<div id="tabs">
		<ul>
		{% for kategorija, _, _ in kategorijas %}
			<li><a href="#tabs-{{ kategorija.pk }}">{{ kategorija.ime }}</a></li>
		{% endfor %}
		</ul>
		{% for kategorija, ekipas, all_added in kategorijas %}
		<div id="tabs-{{ kategorija.pk }}">
			<ul>
			{% for ekipa in ekipas %}
				<li><a href="{% url 'struktura:rezultat_edit' key ekipa.pk %}">{{ ekipa }}</a> <button href="{% url 'struktura:rezultat_rm' key ekipa.pk %}" class='ui-icon ui-icon-trash delete-rezultat'></li>
			{% endfor %}
			{% if not all_added %}
				<li><a href="{% url 'struktura:rezultat_add' key kategorija.pk %}"><span class='ui-icon ui-icon-plus'></span>Dodaj rezultat</a></li>
			</ul>
			{% endif %}
		</div>
		{% endfor %}
	</div>
	<p><b>Navodila za uporabo:</b></p>
	<p>Tukaj so navodila za uporabo. Ce se kej zatakne, sem (JS) dosegljiv na 041 845 674 in <a href=mailto:jakob.schrader@guest.arnes.si">jakob.schrader@guest.arnes.si</a></p>
	<p>V različnih zavihkih so zbrane ekipe različnih kategorij. Med zavihki menjavaš tko, da klikneš tistega, ki te zanima.</p>
	<p>Dodaj rezultat je link, ki te popelje na stran, kjer vneseš rezultate ekipe. Ta link naj bi bil viden za vsako kategorijo dokler nisi za vse ekipe te kategorije vnesel rezultatov.</p>
	<p>Ko neki ekipi dodaš rezultat, se na tej osnovni strani pojavi v neoštevilčenem seznamu. Če hočeš kasneje spremenit kaj od tega, kar si vnesel, klikneš na link. Tako lahko npr. ko ekipa pride na KT vneseš da so prišli in šele kasneje njihove točke po opravljanju nalog(e).</p>
	<p>Za vsakim linkom za ekipo je ikonca smetnjaka. Ta pobriše dodane rezultate za ekipo. Da na smetnjak ne pritisneš po nesreči, je nastavljeno, da moraš nanj izvest dvojni klik (doubleclick).</p>
	<p>Ko si za vse ekipe dodal rezultate in eno izbrišeš, se povezava 'Dodaj rezultat' ne vrne. V tem primeru samo na novo naloži stran.</p>
	<p>In ja, navodila so na dnu. Ko imaš vnesenih malo ekip, naj bi bila dovolj očitna, kasneje pa te ne bodo silili k neskončnem scrollanju.</p>

	<p>Enkrat ko imate čas, dajte prosim rešit še tole kratko <a href="https://docs.google.com/forms/d/e/1FAIpQLSc4W3hwB4vEVG3T9pJV3sYnxOQHEwzkrPCKyvQqQGSnZaipEA/viewform">anketo</a> (majkemi, da je kratka, ma 4 vprašanja, od tega je eno obvezno). Hvala :)</p>
{% endblock content %}

struktura/templates/struktura/rezultat_add.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Volčjak struktura rezultati {{ tekmovanje }} {% endblock %}

{% block content %}
	<h1>Dodajanje rezultatov ({{ kontrola.ime}}):</h1>
	<fieldset>
		<legend>KT: {{ kontrola.ime }}</legend>
		<form action="{% url 'struktura:rezultat_add' key kategorija.pk %}" method="post">
			{% csrf_token %}
			{{ base_form.as_p }}
			{% for naloga, formset in formsets %}
			{{ formset.management_form }}
			{{ formset.as_p }}
			{% endfor %}
			{% for butval in submit_buttons %}
			<input type="submit" value="{{ butval.val }}" name="{{ butval.name }}"/>
			{% endfor %}
		</form>
	</fieldset>
	<p>Tukaj vneseš 'rezultat' za določeno ekipo. Kar shraniš lahko kasneje še spremeniš, tako da raje shranjuj bolj kot manj pogosto.</p>
	<p>Ekipe, ki jih lahko izbereš so tiste, ki ob času nalaganja te strani še niso imele vnesenega rezultata.</p>
	<p>Mrtvi čas vpišeš v prostor mrtvi čas, prostor čas je pa za čas prihoda ekipe na KT. Za vse časovne vrednosti je najbolje, če jih popraviš v formatu, v katerem ti jih volčjak ponudi.</p>
	<p>Morebitne druge naloge, ki jih ekipa opravlja na KT-ju naj bi bile intuitivne za rešit.</p>
	<p>Gumbi so poimenovani čim bolj opisno in počnejo, kar piše na njih. Prikažejo se samo smiselni (npr. ko dodajaš zadnjo ekipo ni več smiselno, da bi shranil in dodal nov rezultat, ker bodo po tej shranitvi vse ekipe te kategorije na tvojemu KT-ju že imele rezultat).</p>
	<p>Gumb prekliči trenutno dela samo, ko si že izbral_a ekipo (v tem primeru je vseeno, katero izbereš). Je pa prekliči v bistvu samo povezava nazaj na osnovno stran.</p>
	<p>Če ti pri shranjevanju volčjak javi napako, jo prosim poskusi razumeti. Če napake ne razumeš in ali misliš, da vse delaš prav, pa me le kontaktiraj (JS: 041 845 674 in <a href=mailto:jakob.schrader@guest.arnes.si">jakob.schrader@guest.arnes.si</a>).</p>
{% endblock content %}

struktura/templates/struktura/tekmovanje.html
{% extends 'struktura/base.html' %}
{% load static %}

{% block title %}Volčjak struktura tekmovanje {{ tekmovanje }} {% endblock %}

{% block content %}
	<h1>Tekmovanje</h1>
	<form action="{% url 'struktura:tekmovanje' key %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="shrani"/>
	</form>
{% endblock content %}