pregled/urls.py
from django.urls import path, register_converter
from django.conf import settings

from . import views
import converters

register_converter(converters.makeConverter(settings.HASHIDS_SALT['main']), 'mhash')
register_converter(converters.makeConverter(settings.HASHIDS_SALT['ekipa']), 'ehash')
register_converter(converters.makeConverter(settings.HASHIDS_SALT['info']), 'ihash')
register_converter(converters.makeConverter(settings.HASHIDS_SALT['rez_view']), 'rv_hash')

app_name = 'pregled'
urlpatterns = [
    path('<mhash:key>/', views.index, name = 'index'),
    path('import_export/<mhash:key>/', views.file.import_export, name = 'import_export'),
    path('download/<mhash:key>/', views.file.download, name = 'download'),
    path('upload/<mhash:key>/', views.file.upload, name = 'upload'),
    path('kontrole/<mhash:key>/', views.kontrole, name = 'kontrole'),
    path('proge/<mhash:key>/', views.proge, name = 'proge'),
    path('ekipe/<mhash:key>/', views.ekipe, name = 'ekipe'),
    path('rezultati/<mhash:key>/', views.rezultati, name = 'rezultati'),
    path('rezultati/v/<rv_hash:key>/', views.rezultati_v, name = 'rezultati_v'),

    path('info/<mhash:key>/<int:ekipa_id>/', views.info.ekipa, name = 'info_ekipa'),
    path('info/<mhash:key>/', views.info.index, name = 'info_index'),
    path('info/<ihash:key>/<str:ime>/', views.info.view, name = 'info_view'),
    path('info/<ihash:key>/', views.info.view, name = 'info_view'),

    path('obvestila/<mhash:key>/', views.obvestilo.obvestila, name = 'obvestila'),
    path('obvestilo/<mhash:key>/<int:obvestilo_id>', views.obvestilo.obvestilo,
        name = 'obvestilo'),
    path('obvestilo/<mhash:key>/new', views.obvestilo.novo_obvestilo,
        name = 'novo_obvestilo'),
    path('obvestilo/<mhash:key>/brisi/<int:obvestilo_id>', views.obvestilo.del_obvestilo,
        name = 'del_obvestilo'),

    path('qr_kontrole/<mhash:key>/', views.qr.kontrole, name = 'qr_kontrole'),
    path('qr_ekipe/<mhash:key>/', views.qr.ekipe, name = 'qr_ekipe'),

    path('<ehash:key>/', views.ekipa.index, name = 'ekipa_index'),
    path('obvestila/<ehash:key>/', views.ekipa.obvestila,
        name = 'ekipa_obvestila'),
    path('obvestila/<ehash:key>/mark_read/<int:obvestilo_id>',
        views.ekipa.mark_read, name = 'mark_read'),
    path('info/<ehash:key>/', views.ekipa.info, name = 'ekipa_info'),
]

struktura/urls.py
from django.urls import path, register_converter
from django.conf import settings

from . import views
import converters

register_converter(converters.makeConverter(
    settings.HASHIDS_SALT['rezultat']), 'rhash')
register_converter(converters.makeConverter(
    settings.HASHIDS_SALT['struktura']), 'shash')
register_converter(converters.makeConverter(
    settings.HASHIDS_SALT['kontrola']), 'khash')

app_name = 'struktura'
urlpatterns = [
    path('tekmovanje/<shash:key>/', views.v_tekmovanje, name='tekmovanje'),
]

for modelname in ['kategorija', 'dan', 'kt', 'ekipa', 'proga', 'kontrola', 'naloga']:
    for op in ['', 'edit', 'add', 'rm']:
        cname = modelname
        if op != '':
            cname += '_' + op
        cpath = cname.replace('_', '/') + '/<shash:key>/'
        if op in ['edit', 'rm']:
            cpath += '<shash:obj_key>/'
        cview = getattr(views, 'v_' + cname),
        urlpatterns.append(path(cpath, *cview, name=cname))

urlpatterns.append(path('rezultat/<khash:key>', views.v_rezultat, name='rezultat'))
urlpatterns.append(path('rezultat/a/<khash:key>/<khash:kat_key>', views.v_rezultat_add, name='rezultat_add'))
urlpatterns.append(path('rezultat/e/<khash:key>/<khash:eki_key>', views.v_rezultat_edit, name='rezultat_edit'))
urlpatterns.append(path('rezultat/r/<khash:key>/<khash:eki_key>', views.v_rezultat_rm, name='rezultat_rm'))

urlpatterns.append(path('rezultati/<rhash:key>/',
                        views.rezultati, name='rezultati'))
urlpatterns.append(path('pregled_ekipe/<rhash:key>/',
                   views.pregled_ekipe, name='pregled_ekipe'))

volcjak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('struktura/', include('struktura.urls')),
    path('pregled/', include('pregled.urls')),
    path('admin/', admin.site.urls),
    path('qr_code/', include('qr_code.urls', namespace='qr_code')),
]

struktura/models/ekipa.py
from django.db import models
from django.contrib import admin
from django.utils.html import format_html
from django.urls import reverse
from django.utils import timezone


class Ekipa(models.Model):

    kategorija = models.ForeignKey('Kategorija', on_delete=models.CASCADE)
    stevilka = models.SmallIntegerField('številka')
    rod = models.CharField(max_length=100)
    ime = models.CharField(max_length=50)
    kontakt = models.CharField(max_length=50, blank=True)
    st_clanov = models.SmallIntegerField('število članov', default=5)
    v_konkurenci = models.BooleanField('v konkurenci', default=True)
    info = models.JSONField(null=True, blank=True)
    cip_id = models.CharField('id čipa', max_length=20, blank=True)

    class Meta:
        ordering = ['kategorija', 'stevilka']
        verbose_name_plural = 'ekipe'

    def __str__(self):
        return f"{self.kategorija} {self.stevilka} {self.ime}"

    @admin.display
    def pregled_link(self):
        return format_html("<a href='{}'>pregled</a>",
                           reverse('pregled:ekipa_index', args=[self.pk]),
                           )

    @classmethod
    def make_ekipa(cls, obj):
        for pk, ekipa in obj['Ekipa'].items():
            obj['Ekipa'][pk] = cls(kategorija=obj['Kategorija'][ekipa['kategorija']])
            for attr, val in ekipa.items():
                if attr == 'kategorija':
                    continue
                setattr(obj['Ekipa'][pk], attr, val)
            obj['Ekipa'][pk].save()
        if 'Rezultat' in obj:
            from . import Rezultat
            Rezultat.make_rezultat(obj)
            #   Sorting subclasses by name is good, because ciljs have to be added
            #   before starts and 'C' < 'S'.
            for rez_subclass in sorted(Rezultat.__subclasses__(), key=lambda subclass: subclass.__name__):
                if rez_subclass.__name__ in obj:
                    rez_subclass.make_rezultat(obj)

    def get_ekipa(self, selection, obj):
        if selection['Rezultat']:
            for rezultat in self.rezultat_set.all():
                rezultat = rezultat.child_obj
                obj[type(rezultat).__name__][rezultat.pk] = rezultat.get_rezultat()
        return {'kategorija': str(self.kategorija.pk), 'stevilka': self.stevilka,
                'rod': self.rod, 'ime': self.ime, 'kontakt': self.kontakt,
                'st_clanov': self.st_clanov, 'v_konkurenci': self.v_konkurenci,
                'info': self.info, 'cip_id': self.cip_id}

    @property
    def tekmovanje(self):
        return self.kategorija.tekmovanje

    @property
    def short_name(self):
        return "<" + str(self.stevilka) + "> [" + self.rod + "] " + self.ime

    @property
    def rezultati(self):
        from . import RezKT
        rez = {'pk': self.pk, 'ime': self.ime, 'obscur': not self.v_konkurenci,
               'values': {'stevilka': self.stevilka,
                          'ime': self.ime,
                          'rod': self.rod,
                          'skupaj': 0,
                          },
               'urls': {
                   },
               }
        for rezultat in self.rezultat_set.all():
            if rezultat.kontrola.pk not in rez['values']:
                rez['values'][rezultat.kontrola.pk] = 0
            if type(rezultat.child_obj) == RezKT:
                if 'KT-ji' not in rez['values']:
                    rez['values']['KT-ji'] = 0
                rez['values']['KT-ji'] += rezultat.tocke
            else:
                rez['values'][rezultat.kontrola.pk] += rezultat.tocke
                rez['urls'][rezultat.kontrola.pk] = reverse('struktura:rezultat_edit',
                                                            args=[rezultat.kontrola.kt.pk, self.pk])
            rez['values']['skupaj'] += rezultat.tocke
        return rez

    @property
    def st_prebranih_obvestil(self):
        return self.obvestilo_set.filter(visible=True).count()

    @property
    def st_neprebranih_obvestil(self):
        return self.kategorija.tekmovanje.st_vidnih_obvestil - \
               self.st_prebranih_obvestil

    def pregled_ekipe(self, proga):
        from . import Rezultat
        from datetime import datetime
        rez = {'pk': self.pk, 'ime': self.ime,
               'values': {
                   'stevilka': self.stevilka,
                   'ime': self.ime,
                   'rod': self.rod,
                   'kontakt': self.kontakt,
               }
        }
        for kontrola in proga.kontrola_set.all():
            if kontrola.naloga_set.exists():
                small = min(map(lambda rez: rez.cas_vnosa, Rezultat.objects.filter(naloga__kontrola=kontrola, ekipa=self)), default=datetime.max)
            else:
                small = ""
            if small != "" and small != datetime.max:
                rez['values'][kontrola.pk] = small.astimezone(timezone.get_current_timezone()).strftime("%H:%M")
        return rez

    def remove_children(self):
        self.rezultat_set.all().delete()

pregled/views/forms.py
from django import forms


class DownloadTekmovanjeForm(forms.Form):

    Dan = forms.BooleanField(initial=True, required=False)
    Kategorija = forms.BooleanField(initial=True, required=False)
    KT = forms.BooleanField(label="KT", initial=True, required=False)
    Proga = forms.BooleanField(initial=True, required=False)
    Kontrola = forms.BooleanField(initial=True, required=False)
    Ekipa = forms.BooleanField(initial=True, required=False)
    Naloga = forms.BooleanField(initial=True, required=False)
    Rezultat = forms.BooleanField(initial=False, required=False)
    pretty = forms.BooleanField(initial=False, required=False)


class UploadTekmovanjeForm(forms.Form):

    action = forms.IntegerField(initial=0,
            widget=forms.Select(choices=[[0, "zamenjaj"], [1, "dodaj"]]))
    struktura_file = forms.FileField(label="Strukturna datoteka")

pregled/views/ekipa.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import loader

from struktura.models import Tekmovanje, Ekipa
from ..models import Obvestilo
from .info import info_imena


def default_context(key):
    context = {'key': key}
    context['ekipa'] = get_object_or_404(Ekipa, pk = key)
    context['tekmovanje'] = context['ekipa'].kategorija.tekmovanje
    context['read'] = context['ekipa'].st_prebranih_obvestil
    context['unread'] = context['ekipa'].st_neprebranih_obvestil
    context['st_obvestil'] = context['tekmovanje'].st_obvestil
    return context


def index(request, key):
    context = default_context(key)
    context['request'] = request
    template = loader.get_template('pregled/ekipa_index.html')
    return HttpResponse(template.render(context, request))


def obvestila(request, key):
    context = default_context(key)
    context['obvestila'] = context['tekmovanje'].obvestilo_set.filter(visible = True)
    template = loader.get_template('pregled/ekipa_obvestila.html')
    return HttpResponse(template.render(context, request))


def mark_read(request, key, obvestilo_id):
    ekipa = get_object_or_404(Ekipa, pk = key)
    obvestilo = get_object_or_404(Obvestilo, pk = obvestilo_id)
    obvestilo.ekipe.add(ekipa)
    return HttpResponse("success!")


def info(request, key):
    context = {'key': key, 'info_imena': info_imena}
    context['ekipa'] = ekipa = get_object_or_404(Ekipa, pk = key)
    context['tekmovanje'] = tekmovanje = ekipa.kategorija.tekmovanje
    template = loader.get_template('pregled/ekipa_info.html')
    return HttpResponse(template.render(context, request))

pregled/views/file.py
import json

from django.urls import reverse
from django.http import HttpResponse, FileResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.files.base import ContentFile

from struktura.models import Tekmovanje
from .forms import DownloadTekmovanjeForm, UploadTekmovanjeForm


def import_export(request, key):
    context = {'key': key}
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk = key)
    context['download_form'] = DownloadTekmovanjeForm()
    context['upload_form'] = UploadTekmovanjeForm()
    return render(request, 'pregled/import_export.html', context)


def download(request, key):
    tekmovanje = get_object_or_404(Tekmovanje, pk = key)
    form = DownloadTekmovanjeForm(request.GET)
    if not form.is_valid():
        raise Http404("Form is invalid!")
    indent = '\t' if form.cleaned_data['pretty'] else ''
    file = ContentFile(json.dumps(tekmovanje.get_tekmovanje(form.cleaned_data), indent=indent).encode())
    response = HttpResponse(file, 'application/json')
    response['Content-Length'] = file.size
    response['Content-Disposition'] = 'attachment; filename="volcjak_{}_{}.json"'.format(tekmovanje.leto, tekmovanje.ime.replace(' ', '_'))
    return response


def upload(request, key):
    tekmovanje = get_object_or_404(Tekmovanje, pk = key)
    form = UploadTekmovanjeForm(request.POST, request.FILES)
    if not form.is_valid():
        raise Http404(f"Form is invalid! {form.errors}")
    obj = json.load(form.cleaned_data['struktura_file'])
    if form.cleaned_data['action'] == 0:
        tekmovanje.remove_children()
    tekmovanje.make_tekmovanje(obj)
    return HttpResponseRedirect(reverse('pregled:import_export', args=[tekmovanje.pk]))

pregled/views/info.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django import forms
from django.urls import reverse

from struktura.models import Tekmovanje, Ekipa

info_imena = ["topotesti", "vrisovanje", "morse", "spanje"]


class InfoForm(forms.Form):

    topotesti = forms.CharField(required = False)
    vrisovanje = forms.CharField(required = False)
    morse = forms.CharField(required = False)
    spanje = forms.CharField(required = False)


def default_context(key):
    context = {'key': key}
    context['tekmovanje'] = get_object_or_404(Tekmovanje, pk = key)
    context['info_imena'] = info_imena
    return context


def index(request, key):
    context = default_context(key)
    context['kategorije'] = context['tekmovanje'].kategorija_set.all()
    context['request'] = request
    template = loader.get_template('pregled/info.html')
    return HttpResponse(template.render(context, request))


def ekipa(request, key, ekipa_id):
    context = default_context(key)
    context['kategorije'] = context['tekmovanje'].kategorija_set.all()
    context['ekipa'] = ekipa = get_object_or_404(Ekipa, pk = ekipa_id)
    if ekipa.kategorija.tekmovanje != context['tekmovanje']:
        raise Http404('Chosen ekipa is not of the same tekmovanje as your link!')
    if request.method == 'POST':
        form = InfoForm(data = request.POST)
        if form.is_valid():
            ekipa.info = form.cleaned_data
            ekipa.save()
            return HttpResponseRedirect(reverse('pregled:info_index', args = [key]))
    else:
        form = InfoForm(data = ekipa.info)
    context['form'] = form
    template = loader.get_template('pregled/info_ekipa.html')
    return HttpResponse(template.render(context, request))


def view(request, key, ime = 'topotesti'):
    context = default_context(key)
    context['cime'] = ime
    values = {}
    for ekipa in Ekipa.objects.filter(kategorija__tekmovanje = key):
        if (ekipa.info == None) or (not ime in ekipa.info.keys()) or (ekipa.info[ime] == ''):
            continue
        if not ekipa.info[ime] in values.keys():
            values[ekipa.info[ime]] = []
        values[ekipa.info[ime]].append(ekipa)
    context['values'] = values
    template = loader.get_template('pregled/info_view.html')
    return HttpResponse(template.render(context, request))

pregled/views/qr.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import loader

from struktura.models import Tekmovanje, KT, Ekipa, Naloga


def kontrole(request, key):
    context = {'key': key, 'request': request}
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk = key)
    context['elementi'] = []
    for kt in KT.objects.filter(dan__tekmovanje = key):
        if Naloga.objects.filter(kontrola__kt = kt).exists():
            context['elementi'].append(kt)
    context['view_name'] = 'struktura:rezultat'
    context['title_name'] = 'kontrole'
    return render(request, 'pregled/qr_seznam.html', context)


def ekipe(request, key):
    context = {'key': key, 'request': request}
    context['tekmovanje'] = tekmovanje = get_object_or_404(Tekmovanje, pk = key)
    context['elementi'] = Ekipa.objects.filter(kategorija__tekmovanje = tekmovanje)
    context['view_name'] = 'pregled:ekipa_index'
    context['title_name'] = 'ekipe'
    return render(request, 'pregled/qr_seznam.html', context)

pregled/templates/pregled/base_ekipa_pregled.html
{% extends 'base.html' %}

{% block mainnav %}
<ul>
	<li id="nav-li-index"><a href="{% url 'pregled:ekipa_index' key %}">pregled</a></li>
	{% if ekipa.st_neprebranih_obvestil == 0 %}
	<li id="nav-li-obvestila" class="read">(0/{{ tekmovanje.st_vidnih_obvestil }}) <a href="{% url 'pregled:ekipa_obvestila' key %}">obvestila</a></li>
	{% else %}
	<li id="nav-li-obvestila" class="unread">(<span id="neprebrani_counter">{{ ekipa.st_neprebranih_obvestil}}</span>/{{tekmovanje.st_vidnih_obvestil}}) <a class="unread" href="{% url 'pregled:ekipa_obvestila' key %}">obvestila</a></li>
	{% endif %}
	<li id="nav-li-info"><a href="{% url 'pregled:ekipa_info' key %}">informacije</a></li>
</ul>
{% endblock mainnav %}

pregled/templates/pregled/base_pregled.html
{% extends 'base.html' %}

{% block mainnav %}
<ul>
	<li id="nav-li-admin_index"><a href="{% url 'admin:index' %}">admin</a></li>
	<li id="nav-li-struktura"><a href="{% url 'struktura:tekmovanje' key %}">struktura</a></li>
	<li id="nav-li-index"><a href="{% url 'pregled:index' key %}">pregled</a></li>
	<li id="nav-li-import_export"><a href="{% url 'pregled:import_export' key %}">import/export</a></li>
	{% comment %}
	<li id="nav-li-obvestila"><a href="{% url 'pregled:obvestila' key %}">obvestila</a></li>
	<li id="nav-li-info"><a href="{% url 'pregled:info_index' key %}">info</a></li>
	{% endcomment %}
	<li id="nav-li-kontrole"><a href="{% url 'pregled:kontrole' key %}">kontrole</a></li>
	<li id="nav-li-proge"><a href="{% url 'pregled:proge' key %}">proge</a></li>
	{% comment %}
	<li id="nav-li-ekipe"><a href="{% url 'pregled:ekipe' key %}">ekipe</a></li>
	{% endcomment %}
	<li id="nav-li-rezultati"><a href="{% url 'pregled:rezultati' key %}">rezultati</a></li>
	<li id="nav-li-qr_kontrole"><a href="{% url 'pregled:qr_kontrole' key %}">QR kontrole</a></li>
	{% comment %}
	<li id="nav-li-qr_ekipe"><a href="{% url 'pregled:qr_ekipe' key %}">QR ekipe</a></li>
	{% endcomment %}
</ul>
{% endblock mainnav %}

pregled/templates/pregled/ekipa_obvestila.html
{% extends 'pregled/base_ekipa_pregled.html' %}
{% load pregled_obvestilo %}

{% block scripts %}
{% csrf_token %}
<script>
	const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
	$(document).ready(function(){
			$('#nav-li-obvestila').addClass('nav-selected');
			$('#accordion').accordion({
				collapsible: true,
				active: false,
				activate: function(event, ui){
					if(ui.newHeader.hasClass("unread")){
						$.ajax({
							url: ui.newHeader.attr("href"),
							type: 'POST',
							headers: { 'X-CSRFToken': csrftoken},
							success: function(data, textStatus, xhr){
								ui.newHeader.removeAttr("href");
								ui.newHeader.removeClass("unread");
								ui.newHeader.addClass("read");
								var counter = $("#neprebrani_counter");
								counter.text(counter.text()-1);
								if(counter.text() == "0"){
									var li = counter.closest("li");
									li.addClass("read");
									li.removeClass("unread");
								}
							},
							error: function(xhr, textStatus, ErrorThrown){
								console.log(xhr.responseText);
								var errorMessage = xhr.responseText;
								errorMessage = errorMessage.substring(errorMessage.indexOf('<title>') + 7, errorMessage.indexOf('</title>'));
								alert('Unable to delete item: ' + errorMessage);
							}
						});
					}
				}
			});
		}
	);
</script>
{% endblock scripts %}

{% block title %}Volčjak pregled obvestila {{ ekipa }} {% endblock %}

{% block content %}
<h1>Obvestila</h1>
<div id="accordion">
	{% for obvestilo in obvestila %}
	{% if obvestilo|read:ekipa.id %}
	<h3 class="read">{{ obvestilo }}</h3>
	{% else %}
	<h3 class="unread" href="{% url 'pregled:mark_read' ekipa.id obvestilo.id %}">{{ obvestilo }}</h3>
	{% endif %}
	<div>{{ obvestilo.besedilo }}</div>
	{% endfor %}
</div>
{% endblock content %}

pregled/templates/pregled/import_export.html
{% extends 'pregled/base_pregled.html' %}

{% block title %}Volčjak pregled import/export {{ tekmovanje }} {% endblock %}

{% block scripts %}
<script>
	$(document).ready(function(){
			$('#nav-li-import_export').addClass('nav-selected');
		}
	);
</script>
{% endblock scripts %}

{% block content %}
<h1> Import/export tekmovanje {{ tekmovanje }} </h1>
<p>Importiraj tekmovanje:</p>
<form enctype="multipart/form-data" action="{% url 'pregled:upload' key %}" method="post">
	{% csrf_token %}
	{{ upload_form.as_p }}
	<input type="submit" value="požen"/>
</form>
<br>
<p>Tuki lahko downloadas tekmovanje in ga drgje importas:</p>
<p>Ker so hierarhično nižje tabele odvisne od hierarhično višjih, lahko med sabo
vplivajo. To pomeni, da če npr. izklopiš kontrolo, ne moreš dobiti nalog,
dogodkov, in rezultatov.</p>
<p>Pretty pomeni, da se bo zgeneriran json file lepo izpisal in bo zamaknjen s
tabulatorji ('\t'). Uporabno, če boš ta json sam gledal in/ali ga na roko
spreminjal, drugače pa samo porabi nekaj več prostora.</p>
<form action="{% url 'pregled:download' key %}" method="get">
	{{ download_form.as_p }}
	<input type="submit" value="gib"/>
</form>
{% endblock content %}

pregled/templates/pregled/info.html
{% extends 'pregled/base_pregled.html' %}
{% load volcjak_tags %}
{% load qr_code %}

{% block scripts %}
<script>
	$(document).ready(function(){
			$('#nav-li-info').addClass('nav-selected');
			$("#tabs").tabs();
		}
	);
</script>
{% endblock scripts %}

{% block title %}Volčjak info ekip {{ tekmovanje }} {% endblock %}

{% block content %}
<h1>Informacije</h1>
<p>Informacije vezane na vsako ekipo posebej.</p>
<p>Imena ekip so linkani na njihove informacije, imena stolpcev pa na pregled stvari</p>
<div id="tabs">
	<ul>
		{% for kategorija in kategorije %}
		<li><a href="#tabs-{{ kategorija.pk }}">{{ kategorija.ime }}</a></li>
		{% endfor %}
	</ul>
	{% for kategorija in kategorije %}
	<div id="tabs-{{ kategorija.pk }}">
		<table>
			<tr>
				<th>ekipa</th>
				{% for ime in info_imena %}
				<th><a href="{% url 'pregled:info_view' key ime %}">{{ ime }}</a></th>
				{% endfor %}
			</tr>
			{% for ekipa in kategorija.ekipa_set.all %}
			<tr>
				<td><a href="{% url 'pregled:info_ekipa' key ekipa.pk %}">{{ ekipa.short_name }}</a></td>
				{% for ime in info_imena %}
				<td>{{ ekipa.info|dict_lookup:ime }}</td>
				{% endfor %}
			</tr>
			{% endfor %}
		</table>
	</div>
	{% endfor %}
</div>
<img class="qr-code" src="{% qr_url_from_text key|reverse_f:"pregled:info_view"|full_url:request %}" alt="{{ key|reverse_f:"pregled:info_view"|full_url:request }}">
{% endblock content %}

pregled/templates/pregled/novo_obvestilo.html
{% extends 'pregled/base_pregled.html' %}

{% block scripts %}
{% endblock scripts %}

{% block title %}Volčjak pregled obvestila {{ tekmovanje }} {% endblock %}

{% block content %}
<h1>Novo obvestilo tekmovanja {{ tekmovanje }}</h1>
<form action="{% url 'pregled:novo_obvestilo' key %}" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="shrani"/>
</form>
{% endblock content %}

pregled/templates/pregled/proge.html
{% extends 'pregled/base_pregled.html' %}
{% load static %}

{% block scripts %}
<script src="{% static 'js/simple_table.js' %}"></script>
<script>

	function update(tekmovanje){
		for(var tab of Object.values(tekmovanje['tabs'])){
			var div = $("#tabs-" + tab.pk);
			make_table(div, tab);
		}
	}

	function refresh(){
		$.get("{% url 'struktura:pregled_ekipe' key %}", update);
	}

	$(document).ready(function(){
			$('#nav-li-proge').addClass('nav-selected');
			$("#tabs").tabs();
			$("#refresh_button").click(refresh);
			refresh();
		}
	);

</script>
{% endblock scripts %}

{% block title %}Volčjak pregled proge {{ tekmovanje }} {% endblock %}

{% block content %}
<h1>Proge</h1>
<button id='refresh_button'>Osveži</button>
<div id="tabs">
	<ul>
		{% for proga in proge %}
		<li><a href="#tabs-{{ proga.pk }}">{{ proga.kategorija.ime }} proga {{ proga.start.dan.st }}</a></li>
		{% endfor %}
	</ul>
	{% for proga in proge %}
	<div id="tabs-{{ proga.pk }}">
	</div>
	{% endfor %}
</div>
{% endblock content %}